### PR TITLE
Add -ism flags to include only certain directories

### PR DESCRIPTION
**Pull request by philgayo**
Hello,

In the company I'm working, we had so many folders it was really hard to properly exclude them using the -esm flag, so I added a new -ism flag that defines the only directories to take into account. You can still use exclusions thru the -esm flag but those will be considered only inside the included directories.
I guess this can be usefull to others.
Thanks for the tool by the way.

### CODE REVIEW

**Comment by Laurensvanrun** [comment]
Nice addition, I think it indeed adds great value. Before I can merge it, you have to add unit-tests for your configuration. Will you please do this?

**Comment by philgayo** [comment]
Just added a test (TestIncludeSourceMask) and also fix the 3 that were broken (TestPreParsing, TestNoParameters and TestInvalidParameter).
Please let me know if all is good.
Thanks

**Review by Laurensvanrun — CHANGES_REQUESTED** [review]
Sorry for the delay, I was on holiday. Your test is good to test the `-ism` parameter. However, with this new functionality you have introduced behavior where the user can use `-ism` and `-esm` combined. I prefer to have a test for that too, so that you are sure that the resulting combination is correct.

**Comment by philgayo** [comment]
Hello, sorry for the long delay on my side.
I just took the time to write a new test, please let me know if it's all good for you.
Thanks

**Review by Laurensvanrun — APPROVED** [review]
Nice, thanks for adding this test.

**Pull request merged**
