### PR TITLE
+ New option - codepage of source files. Could be set via command line argument `-cp` or read from DPROJ

### PR DESCRIPTION
**Pull request by Fr0sT-Brutal**
**WARNING** this PR depends on changes made by `feat_read-searchpath-from-dproj` PR.

### CODE REVIEW

**Comment by Laurensvanrun** [comment]
Thanks for your contribution. Can you also add tests for reading this information from the DPROJ?

**Comment by Fr0sT-Brutal** [comment]
Done! I can rebase the commit once you merge feat_read-searchpath-from-dproj for simpler history

**Comment by Laurensvanrun** [comment]
That would be nice, feat_read-searchpath-from-dproj is merged.

**Comment by Fr0sT-Brutal** [comment]
Closed this accidentally by removing branh, so rereated as #11

**Comment by Laurensvanrun** [comment]
I'm I correct that it reads the codepage from the DPROJ by default and that your commandline parameter overrules it? If so, can you please add this as comment in the readme?

**Comment by Fr0sT-Brutal** [comment]
Well, I've short of time currently and can't check but it seems to me that this depends on the order of arguments because DPROJ is read right when the option is encountered. So if `-cp` appears after, it will overwrite the value read from DPROJ

**Comment by Fr0sT-Brutal** [comment]
@Laurensvanrun added the note

**Pull request closed without merging**
